name: with_animation
description: SwiftUI-style declarative animation primitives for Flutter.
version: 0.1.0
repository: https://github.com/tilucasoli/with_animation

environment:
  sdk: ^3.11.0
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
